# It's recommended to change every "XeraTalist" to your servers name

delay: 20 # Delay for each tab update in ticks. 1 second = 20 ticks (changing requires server restart)

tablist:
  header:
    - ""
    - "&l&o&7FR"
    - "&l&o&7OG"
    - ""
  footer:
    - ""
    - "%tps%&3 tps — %players% players — %ping% ping — %uptime% uptime"
    - ""
